### PR TITLE
Add SRELL to C++ benchmarks

### PR DESCRIPTION
**Pull request by data-man**
My results (GCC 9.3, Boost 1.72.0, [SRELL](http://www.akenotsuki.com/misc/srell/en/) 2.611):

> ./benchmark-stl input-text.txt
> 419.547 - 92
> 368.868 - 5301
> 287.053 - 5

> ./benchmark-boost input-text.txt
> 55.4955 - 92
> 57.3546 - 5301
> 17.8586 - 5

> ./benchmark-srell input-text.txt
> 49.0529 - 92
> 51.0204 - 5302
> 16.8144 - 5

### CODE REVIEW

**Comment by mariomka** [comment]
I think you forgot to add something to the Dockerfile?
I get this error:

```
cpp/benchmark.cpp:6:10: fatal error: srell.hpp: No such file or directory
 #include <srell.hpp>
```

**Comment by data-man** [comment]
I don't use Docker so I can't improve it.

**Comment by mariomka** [comment]
Do you know what package for Ubuntu is necessary to install?

**Comment by data-man** [comment]
No I'm Arch Linux user. :)
Maybe wget + zip from http://www.akenotsuki.com/misc/srell/en/#download

**Comment by data-man** [comment]
@mariomka 
Now where is http://www.akenotsuki.com/misc/srell/srell-latest link.
What you prefer for building?
- makefile in `cpp` dir
- shell script

And I'll rework this PR.

**Comment by mariomka** [comment]
@data-man why do you need a makefile or shell script? Isn't it enough to install the library in `Dockerfile` and update `run-benchmarks.php` ?

**Comment by data-man** [comment]
Download the latest version of SRELL in the Dockerfile? Ok.
I hope `unzip' doesn't need to be installed? :)

**Comment by mariomka** [comment]
I think so

**Comment by data-man** [comment]
Please review.

**Comment by mariomka** [comment]
It looks good! Later, I'll review, merge, run and update the results.

Thank you

**Comment by data-man** [comment]
Are you interested in other C/C++ regex engines?

I can to add Oniguruma to C and RE2 to C++.

**Comment by mariomka** [comment]
Yes, of course. For C++ maybe you can use this PR or wait until I'll merge. For C please open a new PR.

**Comment by data-man** [comment]
> wait until I'll merge.

Yes, because new RE-engines will require code refactoring.

> For C please open a new PR.

Got it!

**Comment by mariomka** [comment]
Now, I have an error building `C++ Boost`

```
cpp/benchmark.cpp: In function ‘void measure(const string&, const string&)’:
<command-line>:0:17: error: ‘srell’ does not name a type; did you mean ‘dreml’?
cpp/benchmark.cpp:18:9: note: in expansion of macro ‘REGEX_NAMESPACE’
   const REGEX_NAMESPACE::regex re{pattern};
         ^~~~~~~~~~~~~~~
<command-line>:0:17: error: ‘srell’ has not been declared
cpp/benchmark.cpp:21:8: note: in expansion of macro ‘REGEX_NAMESPACE’
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
        ^~~~~~~~~~~~~~~
cpp/benchmark.cpp:21:81: error: expected primary-expression before ‘,’ token
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                 ^
cpp/benchmark.cpp:21:83: error: ‘end’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                   ^~~
cpp/benchmark.cpp:21:83: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from cpp/benchmark.cpp:2:
/usr/include/c++/7/bits/range_access.h:97:5: note:   ‘std::end’
     end(_Tp (&__arr)[_Nm])
     ^~~
cpp/benchmark.cpp:21:86: error: expected ‘;’ before ‘{’ token
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                      ^
cpp/benchmark.cpp:21:86: error: expected primary-expression before ‘{’ token
cpp/benchmark.cpp:21:86: error: expected ‘)’ before ‘{’ token
cpp/benchmark.cpp:21:90: error: ‘it’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                          ^~
cpp/benchmark.cpp:21:90: note: suggested alternative: ‘int’
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                          ^~
                                                                                          int
cpp/benchmark.cpp:21:96: error: ‘end’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                                ^~~
cpp/benchmark.cpp:21:96: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from cpp/benchmark.cpp:2:
/usr/include/c++/7/bits/range_access.h:97:5: note:   ‘std::end’
     end(_Tp (&__arr)[_Nm])
     ^~~
```

Also, Dockerfile should be updated because syntax is wrong:

```dockerfile
## C++
RUN apt-get install -yq --no-install-recommends \
        libboost-regex-dev && \
    wget -q http://www.akenotsuki.com/misc/srell/srell-latest -O srell.zip && \
    mkdir -p /tmp/srell && \
    unzip srell.zip -d /tmp/srell && \
    cp -p -u /tmp/srell/single-header/srell.hpp /usr/local/include
```

can you take a look?

**Comment by data-man** [comment]
Hm, I tested with all regex-engines without Docker (I don't use it).

I think that's the reason:
> Dockerfile should be updated because syntax is wrong

One moment, please!

**Comment by data-man** [comment]
Done in right way, I hope.

**Comment by mariomka** [comment]
> Also, Dockerfile should be updated because syntax is wrong:
> 
> ```dockerfile
> ## C++
> RUN apt-get install -yq --no-install-recommends \
>         libboost-regex-dev && \
>     wget -q http://www.akenotsuki.com/misc/srell/srell-latest -O srell.zip && \
>     mkdir -p /tmp/srell && \
>     unzip srell.zip -d /tmp/srell && \
>     cp -p -u /tmp/srell/single-header/srell.hpp /usr/local/include
> ```

I mean, this is the code fixed for dockerfile. Then I run the benchmark and I got the error building C++ boost.

**Comment by mariomka** [comment]
For some reason, building boost is failing by changes in c++ file.

```
 g++ -std=c++11 -O3 cpp/benchmark.cpp -DREGEX_NAMESPACE=srell -o cpp/bin/benchmark-srell
cpp/benchmark.cpp: In function ‘void measure(const string&, const string&)’:
<command-line>:0:17: error: ‘srell’ does not name a type; did you mean ‘dreml’?
cpp/benchmark.cpp:18:9: note: in expansion of macro ‘REGEX_NAMESPACE’
   const REGEX_NAMESPACE::regex re{pattern};
         ^~~~~~~~~~~~~~~
<command-line>:0:17: error: ‘srell’ has not been declared
cpp/benchmark.cpp:21:8: note: in expansion of macro ‘REGEX_NAMESPACE’
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
        ^~~~~~~~~~~~~~~
cpp/benchmark.cpp:21:81: error: expected primary-expression before ‘,’ token
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                 ^
cpp/benchmark.cpp:21:83: error: ‘end’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                   ^~~
cpp/benchmark.cpp:21:83: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from cpp/benchmark.cpp:2:
/usr/include/c++/7/bits/range_access.h:97:5: note:   ‘std::end’
     end(_Tp (&__arr)[_Nm])
     ^~~
cpp/benchmark.cpp:21:86: error: expected ‘;’ before ‘{’ token
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                      ^
cpp/benchmark.cpp:21:86: error: expected primary-expression before ‘{’ token
cpp/benchmark.cpp:21:86: error: expected ‘)’ before ‘{’ token
cpp/benchmark.cpp:21:90: error: ‘it’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                          ^~
cpp/benchmark.cpp:21:90: note: suggested alternative: ‘int’
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                          ^~
                                                                                          int
cpp/benchmark.cpp:21:96: error: ‘end’ was not declared in this scope
   for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
                                                                                                ^~~
cpp/benchmark.cpp:21:96: note: suggested alternative:
In file included from /usr/include/c++/7/string:51:0,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/fstream:38,
                 from cpp/benchmark.cpp:2:
/usr/include/c++/7/bits/range_access.h:97:5: note:   ‘std::end’
     end(_Tp (&__arr)[_Nm])
     ^~~
```

If I undo the changes it builds well.

Sorry, but my C++ knowledge is limited.

**Comment by mariomka** [comment]
Ok, I was wrong. SRELL build is failing... Maybe isn't the library in the right place?

**Comment by data-man** [comment]
> Sorry, but my C++ knowledge is limited.

Sorry, but my Docker knowledge is `null`. :)
Maybe problem in rights for dirs? `/tmp/srell` and `/local/include`?
What if extract downloaded `srell.zip` to `cpp` dir?

**Comment by mariomka** [comment]
It's something with `if/include` statements. If I include `srell.hpp` directly it builds successful.

g++ version:

```
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```

**Comment by mariomka** [comment]
Maybe `#elif` isn't supported?

**Comment by data-man** [comment]
> gcc version 7.5.0

Wow! :)

Updated. Recheck, please.

**Comment by mariomka** [comment]
Merged!! Tomorrow I'll update the results.

**Comment by data-man** [comment]
Thank you very much!

Now SRELL has up-to-date mirror: https://github.com/data-man/SRELL

**Pull request merged**
