### PR TITLE
.NET 5 and variable "count" is replaced by "matches.Count".

### PR DESCRIPTION
**Pull request by pcgit2020**

### CODE REVIEW

**Review by mariomka — CHANGES_REQUESTED** [review]
Thank you!

Please, can you remove `slnx.sqlite` file?

And, what is the motivation to remove count variable? Count should be inside the measurement. I don't know if `matches.Count` is only a getter or it does some work. I prefer to maintain it as a variable to match with all implementations.

**Comment by pcgit2020** [comment]
I did comparing it with Python version yesterday and in Python version is not an extra variable for the count also:
"print(str(elapsed_time * 1e3) + ' - ' + str(len(matches)))" and did not looked at other projects.
I put it back but after stopwatch stop, because this should not be part of regex benchmark.

**Comment by mariomka** [comment]
The statement is "Measures how long it takes to find and count non-overlapping occurrences with default settings."

I will update the Python benchmark.

**Comment by mariomka** [comment]
.NET updated

**Pull request closed without merging**
